name         'ryanuber-packagelist'
version      '0.1.3'
source       'git://github.com/ryanuber/puppet-packagelist'
author       'Ryan Uber'
license      'Apache'
summary      'Package List Puppet Module'
description  'Dynamically create package resources from encoded lists'
project_page 'http://github.com/ryanuber/puppet-packagelist'
