name         'ryanuber-packagelist'
version      '0.2.1'
source       'git://github.com/ryanuber/puppet-packagelist'
author       'Ryan Uber'
license      'MIT'
summary      'Package List Puppet Module'
description  'Dynamically create package resources from lists'
project_page 'http://github.com/ryanuber/puppet-packagelist'
